
services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MySecretPassword123!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app
    deploy:
      placement:
        constraints: [node.role == manager]

  appdocker:
    image: ghcr.io/emanuelbenitezbaez/appdocker:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=AcademiaNovitDB;Username=postgres;Password=MySecretPassword123!
    networks:
      - app
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

volumes:
  pgdata:

networks:
  app:
