
#Nombre del pipeline
name: GH-build-DEV
#Evento que se dispara cuando se pushea a main o se genera un pull request.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#Trabajo de compilación y pruebas.
jobs:
  build:

    runs-on: ubuntu-24.04
     #Pasos del job usando acciones.
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | #Los pares son versiones LTS.
           8.0.x
           9.0.x 
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Enviar email con send-mailer
      if: always()  # Ejecutar incluso si falla el build/test
      uses: devellany/send-mailer@v1.0.2
      with:
        host: app.debugmail.io
        account: ${{ secrets.DEBUGMAIL_USER }}
        password: ${{ secrets.DEBUGMAIL_PASS }}
        sender: GitHub Actions
        from: ${{ secrets.DEBUGMAIL_USER }}@debugmail.io
        to: ${{ secrets.DEBUGMAIL_TO }}
        subject: Resultado del pipeline GH-build-DEV
        body: |
          El workflow ha finalizado.<br/>
          Estado: ${{ job.status }}<br/>
          Rama: ${{ github.ref }}<br/>
          Commit: ${{ github.sha }}
        contentType: text/html
