#Nombre del pipeline
name: GH-build-on-server-DEV
#Evento que se dispara cuando se pushea a main o se genera un pull request.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#Trabajo de compilación y pruebas.
jobs:
  build:

    runs-on: ubuntu-24.04
     #Pasos del job usando acciones.
    steps:

     - name: Build and publish on remote server
       uses: appleboy/ssh-action@v1
       with:
        host: ${{ secrets.VMSERVER_URL_PINGGY }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_PASSWORD_PRIVATE_KEY }}
        port: ${{ secrets.VMSERVER_PORT_PINGGY }}
        script: |
         rm -rf AcademiaNovit2025 || true
         git clone https://github.com/emanuelbenitezbaez/AcademiaNovit2025.git
         cd AcademiaNovit2025/AcademiaNovit
         dotnet build
         dotnet publish -c Release -o ./publish


          
